title: Richard's Blog
name: Richard Gross
user_description: Developer
profile_pic: /assets/img/profile.jpg
favicon: /assets/img/favicon.ico
copyright_name: Richard Gross
url: # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl: # the subpath of your site, e.g. "/blog"
encoding: utf-8

# Build settings
theme: null
plugins:
  - jekyll-feed 
  - jekyll-sitemap
  - jekyll-asciidoc

sass:
  style: compressed

collections:
    notes:
      output: true
      permalink: /notes/:title

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:title
      content-type: post
  - scope:
      path: ""
      type: notes
    values:
      layout: post
      content-type: notes
